// frontend/web/src/Components/UserItem.jsx
import React, { useState } from "react";

const UserItem = ({ user }) => {
  const [hoverCanBtn, setHoverCanBtn] = useState(false);
  const [hoverEditBtn, setHoverEditBtn] = useState(false);

  return (
    <>
      <hr />
      <div className="row">
        <div className="col-11 align-items-center d-flex gap-4">
          <span>
            <strong>ID:</strong> {user.usuario_id}
          </span>
          <span>
            <strong>NOMBRES:</strong>
            {user.nombre}
          </span>
          <span>
            <strong>EMAIL:</strong>
            {user.email}
          </span>
          <span>
            <strong>MONEDA PREFERIDA:</strong>
            {user.moneda_preferida}
          </span>
        </div>
        <div className="col-1">
          <button
            className="btn btn-outline-danger"
            onMouseEnter={() => {
              setHoverCanBtn(true);
            }}
            onMouseLeave={() => {
              setHoverCanBtn(false);
            }}
            onFocus={() => {
              setHoverCanBtn(true);
            }}
            onPointerLeave={() => {
              setHoverCanBtn(false);
            }}
          >
            <i
              className={!hoverCanBtn ? "bi bi-trash3" : "bi bi-trash3-fill"}
            ></i>
          </button>
          <button
            className="btn btn-outline-primary"
            onMouseEnter={() => {
              setHoverEditBtn(true);
            }}
            onMouseLeave={() => {
              setHoverEditBtn(false);
            }}
            onFocus={() => {
              setHoverEditBtn(true);
            }}
            onPointerLeave={() => {
              setHoverEditBtn(false);
            }}
            onBlur={() => {
              setHoverEditBtn(false);
            }}
          >
            <i
              className={hoverEditBtn ? "bi bi-pencil-fill" : "bi bi-pencil"}
            ></i>
          </button>
        </div>
      </div>
      <hr />
    </>
  );
};

export default UserItem;

// frontend/escritorio/src/components/UserItem.vue
<template>
  <div class="card mb-3">
    <div class="card-body d-flex justify-content-between align-items-center">
      <div>
        <h5 class="card-title">ID: {{ user.usuario_id }}</h5>
        <p class="card-text"><strong>Nombre:</strong> {{ user.nombre }}</p>
        <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
        <p class="card-text">
          <strong>Moneda Preferida:</strong> {{ user.moneda_preferida }}
        </p>
      </div>
      <div class="btn-group" role="group">
        <button
          class="btn btn-danger"
          data-bs-toggle="tooltip"
          data-bs-placement="top"
          title="Eliminar Usuario"
          @click="$emit('delete-user', user.usuario_id)"
        >
          <i class="bi bi-trash"></i>
        </button>
        <button
          class="btn btn-primary"
          data-bs-toggle="tooltip"
          data-bs-placement="top"
          title="Editar Usuario"
          @click="$emit('edit-user', user.usuario_id)"
        >
          <i class="bi bi-pencil"></i>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    user: {
      type: Object,
      required: true,
    },
  },
  emits: ["delete-user", "edit-user"],
};
</script>

<style scoped>
.btn-group .btn {
  transition: transform 0.2s ease-in-out;
}

.btn-group .btn:hover {
  transform: scale(1.1);
}
</style>
